version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "hello-world.seadev.io"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm i
    build:
        commands:
            - echo Build started on `date`
            - ng build && ng serve
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes